### ISSUE TITLE
Listener for child and parent node

### ISSUE THREAD

**Issue by vacvac** [EverythingMe/plaxien#2]
How i implement listener for child and parent node ?

**Comment by sromku** [comment]
@vacvac what do you mean by listener for node? I mean, the tree view is a snapshot of your structured data which you put as nodes. Can you give the exact scenario of possible usage of such listeners?

If I understood you currently, then you would like something like:

``` java
Explain.Node node = new Explain.Node("parent node", null);
node.addOnChildrenListener(new OnChildrenListener() {
    void onChangedValue(String name, String value){
        // will be called when one of the values was changed
    }
});
```

Let me know if I got you :)

**Comment by dvirsky** [comment]
I'm not sure this is useful. The idea is that the data is static and a snapshot at a given moment. Please provide a use case.

**Comment by vacvac** [comment]
Thanks sromku I want make data static, when my user click on child or parent node to show another activity

**Comment by dvirsky** [comment]
@vacvac that's actually quite usefuly, especially for value nodes, I actually have a use case for this myself. I'll add it.

**Comment by sromku** [comment]
@vacvac now, i got it :) @dvirsky is on it

**Comment by dvirsky** [comment]
It's not that trivial though if you're using the explain activity, since the node tree is serialized to disk before we launch that activity. So click handlers will be lost.
If you're using the ExplainView in your own activity it's not a problem since no serialization takes place. 

For use case of the explain activity, it's better to set an onClickIntent or something like that, that could be launched when the user clicks the node.

**Comment by dvirsky** [comment]
@vacvac I've implemented something that I hope will answer your need. 

Basically, when you add a value node, you can set a Uri or an intent to be launched when the value node is clicked.

e.g.

``` java
node.addChild("Reasons to build it").
   .addValue("Export the explains", true, "http://everything.me"); //this will launch the browser
   .addValue("Export the explains", true, someCustomIntent); //this will launch an activity from this intent
```

**Comment by sromku** [comment]
commit #414d5ae7c3184ac63e6a6e2c59fa6a54f0561561

**Comment by sromku** [comment]
commit #414d5ae
