### ISSUE TITLE
Export to image or pdf file

### ISSUE THREAD

**Issue by vacvac** [EverythingMe/plaxien#3]
How can I view the last child if i have more than 50 nodes ? It'll be nice if it export to image or pdf.

Something like this : 

https://play.google.com/store/apps/details?id=com.drawexpress.lite&hl=en

https://lh6.ggpht.com/lRMKYxwX7f-5tXfbSAF-hbnre3wvpljds-EJ8kOHs9cCLXdNPSAloEQG7SFOIG66UDI1=h900-rw

**Comment by sromku** [comment]
@vacvac These are indeed very cool and beautiful outputs, but they are very specific to your own implementations. You can export to json with this lib and from on, create any output you need with your own code or other tools.
